apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram-notifier
        type: telegram
        settings:
          bottoken: $TELEGRAM_BOT_TOKEN
          chatid: !!str 138372197
          message: "{{ range .Alerts }}[homelab] {{ if eq .Status \"firing\" }}ðŸ”´ {{ .Annotations.summary }}: {{ .Annotations.value }}{{ else }}âœ… {{ .Annotations.summary_ok }}: {{ .Annotations.value }}{{ end }}\n{{ end }}"
        disableResolveMessage: false
